# Generated by Django 4.2.6 on 2023-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(max_length=250)),
                ("pais", models.CharField(max_length=50)),
                ("quantidade", models.IntegerField()),
            ],
        ),
    ]
